### ISSUE TITLE
Some hints for existing projects to adopt this tool

### ISSUE THREAD

**Issue by lextm** [real-yfprojects/sphinx-polyversion#11]
This is a very nice tool.

For a project created without this in mind, we found the following hints might make the adoption smoother. [PySNMP](https://github.com/lextudio/pysnmp) will be used as an example.

1. Find a main branch to build all the artifacts for deployment, such as `docs`.
2. Decide what to add to the version list. [We chose a few version tags explicitly](https://github.com/lextudio/pysnmp/blob/docs/docs/poly.py#L14), since only a few versions are fully supported. And we skip all branches by using a pattern that never matches.
3. For sphinx documentation itself, the versioning HTML elements need to be added to the theme as documented, so we have [a dedicated commit](https://github.com/lextudio/pysnmp/commit/caef832b19bb012f6a7816f109571a662091bab5) and then cherry-pick it to all related release branches. Without this step the old versions don't have the versioning elements.

In the end, tag those specific versions and test locally if everything builds correctly.

Another thing this tool can’t help is to forward old URLs to the versioned URLs. But if you’re familiar with the web servers you’re using to host the docs site (nginx/IIS for instance), the rewrite rules are still simple to author.

**Comment by real-yfprojects** [comment]
Hi @lextm, thank you for showing interest and sharing some experience.
I'd like to include your hints in the documentation where suitable.



> 1. Find a main branch to build all the artifacts for deployment, such as `docs`.

I didn't talk about this in the docs since I inexplicitely assumed to be working on the `main` branch. Do you think I should make that explicit? Also, why did you decide to build the docs on a dedicated branch?



> 2\. since only a few versions are fully supported. And we skip all branches by using a pattern that never matches.

Since branch and tag patterns have to match the ref name fully, you can use the empty string instead.
This will be specified in the docs once I add documentation for all the constructor parameters - I plan to autogenerate these from the existing code comments.

> 3\. Without this step the old versions don't have the versioning elements.

Yeah, old versions still build with their old sphinx setup including its html theme. This is a design decision I made because I feel like anything else would get to complicated. I think adding a HowTo-Guide for this cherry-picking setup would be nice though - I will add it to the TODO list. Do you have an automated script for that?

**Comment by lextm** [comment]
@real-yfprojects Please feel free to incorporate any useful contents to the documentation of this project and hope that can help more developers.

> Do you think I should make that explicit?

I think making it explicit can be a good idea, as developers might place their documentation on a totally different branch than main.

> Also, why did you decide to build the docs on a dedicated branch?

I have to use main and docs branches separately because the documentation is ultimately hosted on Cloudflare Pages, which has Preview (mapped to main) and Production (mapped to docs) environments.

> you can use the empty string instead.

Right. That is the easiest way.

> This is a design decision I made because I feel like anything else would get to complicated.

I immediately thought of that too, and I believe you made a good decision. Users of this tool might need some help figuring out what they need to do, because they might not be quite familiar with Python/Sphinx like us.

> Do you have an automated script for that?

Sadly of all projects I have right now, only this PySNMP project requires multiple versions to be hosted together. Thus, I did everything manually right now, and don't have an automated script.
